export const QUESTION_BANK = [
  // TRANSPORT
  {
    id: 1,
    text: 'On average, how many miles did you travel by car per day?',
    unit: 'miles',
    min: 0,
    max: 100,
    avgValue: 15,
    co2PerUnit: 251,
    type: 'input',
  },
  {
    id: 2,
    text: 'On average, how many miles did you travel by bus per day?',
    unit: 'miles',
    min: 0,
    max: 50,
    avgValue: 3,
    co2PerUnit: 89,
    type: 'input',
  },
  {
    id: 3,
    text: 'On average, how many miles did you travel by train per day?',
    unit: 'miles',
    min: 0,
    max: 50,
    avgValue: 2,
    co2PerUnit: 41,
    type: 'input',
  },
  {
    id: 4,
    text: 'On average, how many miles did you travel by bicycle per day?',
    unit: 'miles',
    min: 0,
    max: 20,
    avgValue: 1,
    co2PerUnit: 0,
    type: 'input',
  },
  {
    id: 5,
    text: 'How many days did you use a carpool this week?',
    unit: 'days',
    min: 0,
    max: 7,
    avgValue: 2,
    co2PerUnit: 150,
    type: 'slider',
  },
  {
    id: 6,
    text: 'How many flights did you take this month?',
    unit: 'flights',
    min: 0,
    max: 10,
    avgValue: 0.2,
    co2PerUnit: 90000,
    type: 'slider',
  },
  {
    id: 7,
    text: 'How many rideshare trips (Uber/Lyft) did you take this week?',
    unit: 'trips',
    min: 0,
    max: 14,
    avgValue: 2,
    co2PerUnit: 251,
    type: 'slider',
  },
  {
    id: 8,
    text: 'How many times did you walk instead of drive this week?',
    unit: 'times',
    min: 0,
    max: 14,
    avgValue: 3,
    co2PerUnit: 0,
    type: 'slider',
  },
  {
    id: 9,
    text: 'How many times did you use public transit this week?',
    unit: 'times',
    min: 0,
    max: 14,
    avgValue: 4,
    co2PerUnit: 89,
    type: 'slider',
  },
  {
    id: 10,
    text: 'How many miles did you travel by electric scooter per week?',
    unit: 'miles',
    min: 0,
    max: 50,
    avgValue: 2,
    co2PerUnit: 21,
    type: 'input',
  },

  // WATER
  {
    id: 11,
    text: 'On average, how many minutes did you shower per day?',
    unit: 'min',
    min: 0,
    max: 30,
    avgValue: 8,
    co2PerUnit: 8,
    type: 'input',
  },
  {
    id: 12,
    text: 'How many times did you leave the tap running while brushing your teeth this week?',
    unit: 'times',
    min: 0,
    max: 14,
    avgValue: 3,
    co2PerUnit: 34,
    type: 'slider',
  },
  {
    id: 13,
    text: 'How many baths did you take this week?',
    unit: 'baths',
    min: 0,
    max: 10,
    avgValue: 1,
    co2PerUnit: 1600,
    type: 'slider',
  },
  {
    id: 14,
    text: 'How many times did you wash your hands for more than 30 seconds this week?',
    unit: 'times',
    min: 0,
    max: 21,
    avgValue: 7,
    co2PerUnit: 15,
    type: 'slider',
  },
  {
    id: 15,
    text: 'How many times did you use a dishwasher this week?',
    unit: 'times',
    min: 0,
    max: 14,
    avgValue: 5,
    co2PerUnit: 770,
    type: 'slider',
  },

  // ENERGY
  {
    id: 16,
    text: 'On average, how many hours of TV did you watch per day?',
    unit: 'hr',
    min: 0,
    max: 8,
    avgValue: 2,
    co2PerUnit: 56,
    type: 'slider',
  },
  {
    id: 17,
    text: 'On average, how many hours of computer/laptop use per day?',
    unit: 'hr',
    min: 0,
    max: 12,
    avgValue: 4,
    co2PerUnit: 10,
    type: 'input',
  },
  {
    id: 18,
    text: 'On average, how many hours of phone/tablet use per day?',
    unit: 'hr',
    min: 0,
    max: 15,
    avgValue: 6,
    co2PerUnit: 1.1,
    type: 'input',
  },
  {
    id: 19,
    text: 'On average, how many hours did lights stay on in your bedroom per day?',
    unit: 'hr',
    min: 0,
    max: 24,
    avgValue: 4,
    co2PerUnit: 43,
    type: 'input',
  },
  {
    id: 20,
    text: 'How many times did you charge your phone this week?',
    unit: 'times',
    min: 0,
    max: 10,
    avgValue: 7,
    co2PerUnit: 15,
    type: 'slider',
  },
  {
    id: 21,
    text: 'How many loads of laundry did your family do this week?',
    unit: 'loads',
    min: 0,
    max: 10,
    avgValue: 3,
    co2PerUnit: 275,
    type: 'slider',
  },
  {
    id: 22,
    text: 'How many times did you use a clothes dryer this week?',
    unit: 'times',
    min: 0,
    max: 10,
    avgValue: 2,
    co2PerUnit: 1000,
    type: 'slider',
  },
  {
    id: 23,
    text: 'How many hours did you use air conditioning per day?',
    unit: 'hr',
    min: 0,
    max: 24,
    avgValue: 2,
    co2PerUnit: 50,
    type: 'input',
  },
  {
    id: 24,
    text: 'How many hours did you use a space heater per day?',
    unit: 'hr',
    min: 0,
    max: 24,
    avgValue: 1,
    co2PerUnit: 60,
    type: 'input',
  },

  // FOOD
  {
    id: 25,
    text: 'On average, how many meat meals did you eat per day?',
    unit: 'meals',
    min: 0,
    max: 5,
    avgValue: 1.2,
    co2PerUnit: 644,
    type: 'slider',
  },
  {
    id: 26,
    text: 'On average, how many vegetarian meals did you eat per day?',
    unit: 'meals',
    min: 0,
    max: 5,
    avgValue: 1.8,
    co2PerUnit: 153,
    type: 'slider',
  },
  {
    id: 27,
    text: 'How many fast-food meals did you eat this week?',
    unit: 'meals',
    min: 0,
    max: 14,
    avgValue: 3,
    co2PerUnit: 688,
    type: 'slider',
  },
  {
    id: 28,
    text: 'How many bottles of water did you buy this week?',
    unit: 'bottles',
    min: 0,
    max: 14,
    avgValue: 5,
    co2PerUnit: 83,
    type: 'slider',
  },
  {
    id: 29,
    text: 'How many servings of dairy did you have per day?',
    unit: 'servings',
    min: 0,
    max: 5,
    avgValue: 1.5,
    co2PerUnit: 400,
    type: 'slider',
  },
  {
    id: 30,
    text: 'How many snacks in plastic packaging did you eat this week?',
    unit: 'snacks',
    min: 0,
    max: 14,
    avgValue: 7,
    co2PerUnit: 25,
    type: 'slider',
  },

  // WASTE & CONSUMPTION
  {
    id: 31,
    text: 'How many plastic bags did you use this week?',
    unit: 'bags',
    min: 0,
    max: 14,
    avgValue: 3,
    co2PerUnit: 10,
    type: 'slider',
  },
  {
    id: 32,
    text: 'How many pieces of paper did you throw away this week?',
    unit: 'sheets',
    min: 0,
    max: 50,
    avgValue: 10,
    co2PerUnit: 5,
    type: 'input',
  },
  {
    id: 33,
    text: 'How many times did you forget to recycle this week?',
    unit: 'times',
    min: 0,
    max: 10,
    avgValue: 2,
    co2PerUnit: 50,
    type: 'slider',
  },
  {
    id: 34,
    text: 'How many new items of clothing did you buy this month?',
    unit: 'items',
    min: 0,
    max: 10,
    avgValue: 1,
    co2PerUnit: 2500,
    type: 'slider',
  },
  {
    id: 35,
    text: 'How many online orders did you make this month?',
    unit: 'orders',
    min: 0,
    max: 10,
    avgValue: 2,
    co2PerUnit: 200,
    type: 'slider',
  },
  {
    id: 36,
    text: 'How many hours did you play video games per day?',
    unit: 'hr',
    min: 0,
    max: 8,
    avgValue: 1,
    co2PerUnit: 90,
    type: 'slider',
  },
  {
    id: 37,
    text: 'How many hours did you stream videos per day?',
    unit: 'hr',
    min: 0,
    max: 8,
    avgValue: 2,
    co2PerUnit: 36,
    type: 'slider',
  },
  {
    id: 38,
    text: 'How many times did you leave the lights on in empty rooms this week?',
    unit: 'times',
    min: 0,
    max: 14,
    avgValue: 4,
    co2PerUnit: 43,
    type: 'slider',
  },
  {
    id: 39,
    text: 'How many minutes did you leave the air conditioning running per day?',
    unit: 'min',
    min: 0,
    max: 120,
    avgValue: 30,
    co2PerUnit: 1.5,
    type: 'input',
  },
  {
    id: 40,
    text: 'How many times did you throw food away this week?',
    unit: 'times',
    min: 0,
    max: 14,
    avgValue: 4,
    co2PerUnit: 100,
    type: 'slider',
  },
];
